# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
    os: ubuntu-24.04
    tools:
        nodejs: "22"

    commands:
        # Install Docusaurus dependencies
        - cd docusaurus/ && yarn install
        # Build the site
        - cd docusaurus/ && yarn build
        # Copy generated files into Read the Docs directory
        - mkdir --parents $READTHEDOCS_OUTPUT/html/
        - cp --recursive docusaurus/build/* $READTHEDOCS_OUTPUT/html/


